### ISSUE TITLE
build on master branch is failing for Ubuntu 18.04

### ISSUE THREAD

**Issue by vsharma13** [OpenSSE/opensse-schemes#12]
Dear Rbost,
Building seems failing on Ubuntu 18.04. 
make
Scanning dependencies of target sse_crypto
[  1%] Building CXX object third_party/crypto/src/CMakeFiles/sse_crypto.dir/cipher.cpp.o
[  2%] Building CXX object third_party/crypto/src/CMakeFiles/sse_crypto.dir/key.cpp.o
[  3%] Building CXX object third_party/crypto/src/CMakeFiles/sse_crypto.dir/prg.cpp.o
[  4%] Building CXX object third_party/crypto/src/CMakeFiles/sse_crypto.dir/tdp.cpp.o
[  5%] Building CXX object third_party/crypto/src/CMakeFiles/sse_crypto.dir/prp.cpp.o
[  6%] Building CXX object third_party/crypto/src/CMakeFiles/sse_crypto.dir/hmac.cpp.o
[  8%] Building CXX object third_party/crypto/src/CMakeFiles/sse_crypto.dir/prf.cpp.o
[  9%] Building CXX object third_party/crypto/src/CMakeFiles/sse_crypto.dir/puncturable_enc.cpp.o
In file included from /home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/util.hpp:3:0,
                 from /home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/GMPpke.hpp:11,
                 from /home/vaibhav/opensse-schemes/third_party/crypto/src/puncturable_enc.cpp:23:
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h: In function ‘bool relicxx::operator==(const relicxx::ZR&, const relicxx::ZR&)’:
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:218:33: error: ‘CMP_EQ’ was not declared in this scope
         if (bn_cmp(x.z, y.z) == CMP_EQ) {
                                 ^~~~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:218:33: note: suggested alternative: ‘M_E’
         if (bn_cmp(x.z, y.z) == CMP_EQ) {
                                 ^~~~~~
                                 M_E
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h: In function ‘bool relicxx::operator!=(const relicxx::ZR&, const relicxx::ZR&)’:
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:243:33: error: ‘CMP_EQ’ was not declared in this scope
         if (bn_cmp(x.z, y.z) != CMP_EQ) {
                                 ^~~~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:243:33: note: suggested alternative: ‘M_E’
         if (bn_cmp(x.z, y.z) != CMP_EQ) {
                                 ^~~~~~
                                 M_E
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h: In function ‘bool relicxx::operator>(const relicxx::ZR&, const relicxx::ZR&)’:
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:268:33: error: ‘CMP_GT’ was not declared in this scope
         if (bn_cmp(x.z, y.z) == CMP_GT) {
                                 ^~~~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:268:33: note: suggested alternative: ‘EP_OT’
         if (bn_cmp(x.z, y.z) == CMP_GT) {
                                 ^~~~~~
                                 EP_OT
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h: In function ‘bool relicxx::operator<(const relicxx::ZR&, const relicxx::ZR&)’:
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:293:33: error: ‘CMP_LT’ was not declared in this scope
         if (bn_cmp(x.z, y.z) == CMP_LT) {
                                 ^~~~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:293:33: note: suggested alternative: ‘EP_OT’
         if (bn_cmp(x.z, y.z) == CMP_LT) {
                                 ^~~~~~
                                 EP_OT
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h: At global scope:
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:324:58: error: ‘FP_BYTES’ was not declared in this scope
     constexpr static uint16_t kByteSize        = 1 + 2 * FP_BYTES;
                                                          ^~~~~~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:324:58: note: suggested alternative: ‘FP_QNRES’
     constexpr static uint16_t kByteSize        = 1 + 2 * FP_BYTES;
                                                          ^~~~~~~~
                                                          FP_QNRES
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:325:54: error: ‘FP_BYTES’ was not declared in this scope
     constexpr static uint16_t kCompactByteSize = 1 + FP_BYTES;
                                                      ^~~~~~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:325:54: note: suggested alternative: ‘FP_QNRES’
     constexpr static uint16_t kCompactByteSize = 1 + FP_BYTES;
                                                      ^~~~~~~~
                                                      FP_QNRES
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h: In function ‘bool relicxx::operator==(const relicxx::G1&, const relicxx::G1&)’:
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:415:36: error: ‘CMP_EQ’ was not declared in this scope
         return g1_cmp(x.g, y.g) == CMP_EQ;
                                    ^~~~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:415:36: note: suggested alternative: ‘M_E’
         return g1_cmp(x.g, y.g) == CMP_EQ;
                                    ^~~~~~
                                    M_E
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h: In function ‘bool relicxx::operator!=(const relicxx::G1&, const relicxx::G1&)’:
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:419:36: error: ‘CMP_EQ’ was not declared in this scope
         return g1_cmp(x.g, y.g) != CMP_EQ;
                                    ^~~~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:419:36: note: suggested alternative: ‘M_E’
         return g1_cmp(x.g, y.g) != CMP_EQ;
                                    ^~~~~~
                                    M_E
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h: At global scope:
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:426:58: error: ‘FP_BYTES’ was not declared in this scope
     constexpr static uint16_t kByteSize        = 1 + 4 * FP_BYTES;
                                                          ^~~~~~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:426:58: note: suggested alternative: ‘FP_QNRES’
     constexpr static uint16_t kByteSize        = 1 + 4 * FP_BYTES;
                                                          ^~~~~~~~
                                                          FP_QNRES
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:427:58: error: ‘FP_BYTES’ was not declared in this scope
     constexpr static uint16_t kCompactByteSize = 1 + 2 * FP_BYTES;
                                                          ^~~~~~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:427:58: note: suggested alternative: ‘FP_QNRES’
     constexpr static uint16_t kCompactByteSize = 1 + 2 * FP_BYTES;
                                                          ^~~~~~~~
                                                          FP_QNRES
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h: In function ‘bool relicxx::operator==(const relicxx::G2&, const relicxx::G2&)’:
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:514:70: error: ‘CMP_EQ’ was not declared in this scope
         return g2_cmp(const_cast<G2&>(x).g, const_cast<G2&>(y).g) == CMP_EQ;
                                                                      ^~~~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:514:70: note: suggested alternative: ‘M_E’
         return g2_cmp(const_cast<G2&>(x).g, const_cast<G2&>(y).g) == CMP_EQ;
                                                                      ^~~~~~
                                                                      M_E
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h: In function ‘bool relicxx::operator!=(const relicxx::G2&, const relicxx::G2&)’:
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:518:70: error: ‘CMP_EQ’ was not declared in this scope
         return g2_cmp(const_cast<G2&>(x).g, const_cast<G2&>(y).g) != CMP_EQ;
                                                                      ^~~~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:518:70: note: suggested alternative: ‘M_E’
         return g2_cmp(const_cast<G2&>(x).g, const_cast<G2&>(y).g) != CMP_EQ;
                                                                      ^~~~~~
                                                                      M_E
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h: At global scope:
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:525:55: error: ‘FP_BYTES’ was not declared in this scope
     constexpr static uint16_t kByteSize        = 12 * FP_BYTES;
                                                       ^~~~~~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:525:55: note: suggested alternative: ‘FP_QNRES’
     constexpr static uint16_t kByteSize        = 12 * FP_BYTES;
                                                       ^~~~~~~~
                                                       FP_QNRES
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:526:54: error: ‘FP_BYTES’ was not declared in this scope
     constexpr static uint16_t kCompactByteSize = 8 * FP_BYTES;
                                                      ^~~~~~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:526:54: note: suggested alternative: ‘FP_QNRES’
     constexpr static uint16_t kCompactByteSize = 8 * FP_BYTES;
                                                      ^~~~~~~~
                                                      FP_QNRES
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h: In function ‘bool relicxx::operator==(const relicxx::GT&, const relicxx::GT&)’:
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:613:70: error: ‘CMP_EQ’ was not declared in this scope
         return gt_cmp(const_cast<GT&>(x).g, const_cast<GT&>(y).g) == CMP_EQ;
                                                                      ^~~~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:613:70: note: suggested alternative: ‘M_E’
         return gt_cmp(const_cast<GT&>(x).g, const_cast<GT&>(y).g) == CMP_EQ;
                                                                      ^~~~~~
                                                                      M_E
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h: In function ‘bool relicxx::operator!=(const relicxx::GT&, const relicxx::GT&)’:
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:617:70: error: ‘CMP_EQ’ was not declared in this scope
         return gt_cmp(const_cast<GT&>(x).g, const_cast<GT&>(y).g) != CMP_EQ;
                                                                      ^~~~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:617:70: note: suggested alternative: ‘M_E’
         return gt_cmp(const_cast<GT&>(x).g, const_cast<GT&>(y).g) != CMP_EQ;
                                                                      ^~~~~~
                                                                      M_E
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h: At global scope:
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:80:29: error: ‘RELIC_BN_BITS’ was not declared in this scope
 #define RELIC_BN_BYTES CEIL(RELIC_BN_BITS, 8)
                             ^
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:654:11: note: in expansion of macro ‘RELIC_BN_BYTES’
         = RELIC_BN_BYTES + kStatisticalSecurity / 8;
           ^~~~~~~~~~~~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:80:29: note: suggested alternative: ‘RLC_BN_BITS’
 #define RELIC_BN_BYTES CEIL(RELIC_BN_BITS, 8)
                             ^
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:654:11: note: in expansion of macro ‘RELIC_BN_BYTES’
         = RELIC_BN_BYTES + kStatisticalSecurity / 8;
           ^~~~~~~~~~~~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:80:24: error: ‘CEIL’ was not declared in this scope
 #define RELIC_BN_BYTES CEIL(RELIC_BN_BITS, 8)
                        ^
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:654:11: note: in expansion of macro ‘RELIC_BN_BYTES’
         = RELIC_BN_BYTES + kStatisticalSecurity / 8;
           ^~~~~~~~~~~~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:80:24: note: suggested alternative: ‘CALL’
 #define RELIC_BN_BYTES CEIL(RELIC_BN_BITS, 8)
                        ^
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:654:11: note: in expansion of macro ‘RELIC_BN_BYTES’
         = RELIC_BN_BYTES + kStatisticalSecurity / 8;
           ^~~~~~~~~~~~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/relic_wrapper/relic_api.h:657:60: error: could not convert template argument ‘relicxx::PairingGroup::kPrfOutputSize’ from ‘const unsigned int’ to ‘short unsigned int’
     ZR pseudoRandomZR(const sse::crypto::Prf<kPrfOutputSize>& prf,
                                                            ^
In file included from /home/vaibhav/opensse-schemes/third_party/crypto/src/puncturable_enc.cpp:23:0:
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/GMPpke.hpp:32:61: error: ‘FP_BYTES’ was not declared in this scope
 using PPKE_HKDF = sse::crypto::HMac<sse::crypto::Hash, 12 * FP_BYTES>;
                                                             ^~~~~~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/GMPpke.hpp:32:61: note: suggested alternative: ‘FP_QNRES’
 using PPKE_HKDF = sse::crypto::HMac<sse::crypto::Hash, 12 * FP_BYTES>;
                                                             ^~~~~~~~
                                                             FP_QNRES
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/GMPpke.hpp:32:69: error: template argument 2 is invalid
 using PPKE_HKDF = sse::crypto::HMac<sse::crypto::Hash, 12 * FP_BYTES>;
                                                                     ^
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/GMPpke.hpp:307:58: error: could not convert template argument ‘sse::crypto::kPPKEPrfOutputSize’ from ‘const size_t {aka const long unsigned int}’ to ‘short unsigned int’
     void keygen(const sse::crypto::Prf<kPPKEPrfOutputSize>& prf,
                                                          ^
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/GMPpke.hpp:312:60: error: could not convert template argument ‘sse::crypto::kPPKEPrfOutputSize’ from ‘const size_t {aka const long unsigned int}’ to ‘short unsigned int’
     void paramgen(const sse::crypto::Prf<kPPKEPrfOutputSize>& prf,
                                                            ^
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/GMPpke.hpp:425:50: error: could not convert template argument ‘sse::crypto::kPPKEPrfOutputSize’ from ‘const size_t {aka const long unsigned int}’ to ‘short unsigned int’
         const sse::crypto::Prf<kPPKEPrfOutputSize>& prf,
                                                  ^
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/GMPpke.hpp:429:50: error: could not convert template argument ‘sse::crypto::kPPKEPrfOutputSize’ from ‘const size_t {aka const long unsigned int}’ to ‘short unsigned int’
         const sse::crypto::Prf<kPPKEPrfOutputSize>& prf,
                                                  ^
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/GMPpke.hpp:451:65: error: could not convert template argument ‘sse::crypto::kPPKEPrfOutputSize’ from ‘const size_t {aka const long unsigned int}’ to ‘short unsigned int’
     void keygenPartial(const sse::crypto::Prf<kPPKEPrfOutputSize>& prf,
                                                                 ^
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/GMPpke.hpp:458:74: error: could not convert template argument ‘sse::crypto::kPPKEPrfOutputSize’ from ‘const size_t {aka const long unsigned int}’ to ‘short unsigned int’
     GmppkePrivateKeyShare skgen(const sse::crypto::Prf<kPPKEPrfOutputSize>& prf,
                                                                          ^
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/GMPpke.hpp: In member function ‘sse::crypto::GmmppkeCT<T> sse::crypto::Gmppke::encrypt(const sse::crypto::GmppkePublicKey&, const T&, const tag_type&) const’:
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/GMPpke.hpp:342:34: error: ‘FP_BYTES’ was not declared in this scope
         std::array<uint8_t, 12 * FP_BYTES> gt_blind_bytes;
                                  ^~~~~~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/GMPpke.hpp:342:34: note: suggested alternative: ‘FP_QNRES’
         std::array<uint8_t, 12 * FP_BYTES> gt_blind_bytes;
                                  ^~~~~~~~
                                  FP_QNRES
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/GMPpke.hpp:342:42: error: template argument 2 is invalid
         std::array<uint8_t, 12 * FP_BYTES> gt_blind_bytes;
                                          ^
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/GMPpke.hpp:344:45: error: request for member ‘size’ in ‘gt_blind_bytes’, which is of non-class type ‘int’
             .getBytes(false, gt_blind_bytes.size(), gt_blind_bytes.data());
                                             ^~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/GMPpke.hpp:344:68: error: request for member ‘data’ in ‘gt_blind_bytes’, which is of non-class type ‘int’
             .getBytes(false, gt_blind_bytes.size(), gt_blind_bytes.data());
                                                                    ^~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/GMPpke.hpp:347:34: error: request for member ‘data’ in ‘gt_blind_bytes’, which is of non-class type ‘int’
         hkdf.hmac(gt_blind_bytes.data(),
                                  ^~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/GMPpke.hpp:348:34: error: request for member ‘size’ in ‘gt_blind_bytes’, which is of non-class type ‘int’
                   gt_blind_bytes.size(),
                                  ^~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/GMPpke.hpp: In member function ‘sse::crypto::GmmppkeCT<T> sse::crypto::Gmppke::encrypt(const sse::crypto::GmppkeSecretParameters&, const T&, const tag_type&) const’:
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/GMPpke.hpp:368:34: error: ‘FP_BYTES’ was not declared in this scope
         std::array<uint8_t, 12 * FP_BYTES> gt_blind_bytes;
                                  ^~~~~~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/GMPpke.hpp:368:34: note: suggested alternative: ‘FP_QNRES’
         std::array<uint8_t, 12 * FP_BYTES> gt_blind_bytes;
                                  ^~~~~~~~
                                  FP_QNRES
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/GMPpke.hpp:368:42: error: template argument 2 is invalid
         std::array<uint8_t, 12 * FP_BYTES> gt_blind_bytes;
                                          ^
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/GMPpke.hpp:370:45: error: request for member ‘size’ in ‘gt_blind_bytes’, which is of non-class type ‘int’
             .getBytes(false, gt_blind_bytes.size(), gt_blind_bytes.data());
                                             ^~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/GMPpke.hpp:370:68: error: request for member ‘data’ in ‘gt_blind_bytes’, which is of non-class type ‘int’
             .getBytes(false, gt_blind_bytes.size(), gt_blind_bytes.data());
                                                                    ^~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/GMPpke.hpp:373:34: error: request for member ‘data’ in ‘gt_blind_bytes’, which is of non-class type ‘int’
         hkdf.hmac(gt_blind_bytes.data(),
                                  ^~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/ppke/GMPpke.hpp:374:34: error: request for member ‘size’ in ‘gt_blind_bytes’, which is of non-class type ‘int’
                   gt_blind_bytes.size(),
                                  ^~~~
/home/vaibhav/opensse-schemes/third_party/crypto/src/puncturable_enc.cpp: At global scope:
/home/vaibhav/opensse-schemes/third_party/crypto/src/puncturable_enc.cpp:52:46: error: could not convert template argument ‘sse::crypto::kPPKEPrfOutputSize’ from ‘const size_t {aka const long unsigned int}’ to ‘short unsigned int’
     const sse::crypto::Prf<kPPKEPrfOutputSize> master_prf_;
                                              ^
/home/vaibhav/opensse-schemes/third_party/crypto/src/puncturable_enc.cpp:55:61: error: could not convert template argument ‘sse::crypto::kPPKEPrfOutputSize’ from ‘const size_t {aka const long unsigned int}’ to ‘short unsigned int’
                       == sse::crypto::Prf<kPPKEPrfOutputSize>::kKeySize,
                                                             ^
/home/vaibhav/opensse-schemes/third_party/crypto/src/puncturable_enc.cpp: In constructor ‘sse::crypto::PuncturableEncryption::PEncImpl::PEncImpl(sse::crypto::punct::master_key_type&&)’:
/home/vaibhav/opensse-schemes/third_party/crypto/src/puncturable_enc.cpp:61:33: error: cannot convert ‘std::remove_reference<sse::crypto::Key<32>&>::type {aka sse::crypto::Key<32>}’ to ‘const int’ in initialization
     : master_prf_(std::move(key))
                                 ^
third_party/crypto/src/CMakeFiles/sse_crypto.dir/build.make:230: recipe for target 'third_party/crypto/src/CMakeFiles/sse_crypto.dir/puncturable_enc.cpp.o' failed
make[2]: *** [third_party/crypto/src/CMakeFiles/sse_crypto.dir/puncturable_enc.cpp.o] Error 1
CMakeFiles/Makefile2:1059: recipe for target 'third_party/crypto/src/CMakeFiles/sse_crypto.dir/all' failed
make[1]: *** [third_party/crypto/src/CMakeFiles/sse_crypto.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by rbost** [comment]
Hi!

Nice catch. This is due to a breaking change of the Relic library. I will fix the code so it compiles with the newest version.

**Comment by rbost** [comment]
Fixed in be28a29a25262cb7eb90d1c4215e6713756c8e28.

**Comment by vsharma13** [comment]
Tested and Working
