### ISSUE TITLE
cmake: Could NOT find RocksDB (missing: ROCKSDB_LIBRARIES ROCKSDB_INCLUDE_DIRS)

### ISSUE THREAD

**Issue by lorand1984** [OpenSSE/opensse-schemes#16]
Hi,
When I try to build with cmake, I get this error:

-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_OPT_WALL_SUPPORTED
-- Performing Test COMPILER_OPT_WALL_SUPPORTED - Success
-- Performing Test COMPILER_OPT_WEXTRA_SUPPORTED
-- Performing Test COMPILER_OPT_WEXTRA_SUPPORTED - Success
-- Performing Test COMPILER_OPT_WERROR_SUPPORTED
-- Performing Test COMPILER_OPT_WERROR_SUPPORTED - Success
-- Performing Test COMPILER_OPT_ARCH_NATIVE_SUPPORTED
-- Performing Test COMPILER_OPT_ARCH_NATIVE_SUPPORTED - Success
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find RocksDB (missing: ROCKSDB_LIBRARIES ROCKSDB_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindRocksDB.cmake:35 (find_package_handle_standard_args)
  CMakeLists.txt:82 (find_package)

-- Configuring incomplete, errors occurred!

It seems it looks for a directory named lib that doesn't exist in my rocksdb installation

**Comment by rbost** [comment]
Hi, 
Have you installed the RocksDB library? Without it, it won't even compile.
