### ISSUE TITLE
CMake Error at CMakeLists.txt:2 (project):   project with VERSION must use LANGUAGES before language names.

### ISSUE THREAD

**Issue by xygdys** [OpenSSE/opensse-schemes#17]
When I try to build with cmake,I got this error:
I entered
`mkdir build && cd build`
`cmake ..`
then i got
    CMake Error at CMakeLists.txt:2 (project):
      project with VERSION must use LANGUAGES before language names.

-- Configuring incomplete, errors occurred!

My cmake version is 3.5.1

**Comment by rbost** [comment]
Hi,
I might have not tested the code with an old enough version of `cmake`.
Could you try the following : in `CMakeLists.txt` (at the root of the project), replace
```cmake
project(opensse-schemes VERSION 0.3 DESCRIPTION "OpenSSE's Schemes Implementation")
```
by
```cmake
project(opensse-schemes VERSION 0.3)
```

Let me know if that solves your issue.

**Comment by xygdys** [comment]
> Hi,
> I might have not tested the code with an old enough version of `cmake`.
> Could you try the following : in `CMakeLists.txt` (at the root of the project), replace
> 
> ```cmake
> project(opensse-schemes VERSION 0.3 DESCRIPTION "OpenSSE's Schemes Implementation")
> ```
> 
> by
> 
> ```cmake
> project(opensse-schemes VERSION 0.3)
> ```
> 
> Let me know if that solves your issue.

Thank you,it works.
Is seems that the version of cmake should be higher than 3.9, and there is something wrong in the README.md:
"Building is done using CMake. The minimum required version is CMake 3.1."

**Comment by ManoPrakash6** [comment]
> When I try to build with cmake,I got this error: I entered `mkdir build && cd build` `cmake ..` then i got CMake Error at CMakeLists.txt:2 (project): project with VERSION must use LANGUAGES before language names.
> 
> -- Configuring incomplete, errors occurred!
> 
> My cmake version is 3.5.1

If you have mentioned `LANGUAGE` somewhere in your `CMakeLists.txt`, Try changing `LANGUAGE` to `LANGUAGES` and then run `cmake` command.
