### ISSUE TITLE
Cmake Error:Could NOT find Protobuf (missing: Protobuf_PROTOC_EXECUTABLE) (found   version "3.13.0.0")

### ISSUE THREAD

**Issue by xygdys** [OpenSSE/opensse-schemes#18]
Hi,
When i try to build, i get this error:

cmake ..

CMake Error at /usr/local/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Protobuf (missing: Protobuf_PROTOC_EXECUTABLE) (found
  version "3.13.0.0")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/lib/cmake/protobuf/protobuf-module.cmake:162 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /usr/local/lib/cmake/protobuf/protobuf-config.cmake:149 (include)
  cmake/FindGRPC.cmake:80 (find_package)
  CMakeLists.txt:87 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/zhouyou/opensse-schemes/build/CMakeFiles/CMakeOutput.log".
See also "/home/zhouyou/opensse-schemes/build/CMakeFiles/CMakeError.log".

I have installed protobuf :
protoc --version
libprotoc 3.13.0

**Comment by xygdys** [comment]
I have sovled this problem.
It seems that `protobuf-module.cmake` has a bug: it uses a librariy finding function to find the EXECUTABLE program protoc!!!,  as shown follow:

    _protobuf_find_libraries(Protobuf_PROTOC protoc)     at line 140

thus, i modified `/opensse-schemes/cmake/FindGRPC.cmake` line 80:

    find_package(Protobuf CONFIG REQUIRED)   --->   find_package(Protobuf  REQUIRED) 

to  avoid using CONFIG option of find_package()

**Comment by chrisyy2003** [comment]
very nice
